### ISSUE TITLE
how to compile npml to nml?

### ISSUE THREAD

**Issue by RuiSoft2022** [SylvainDevidal/SNCF#4]
I am new to nml. In the source code, use .pnml as the root file for those nmls. So my question is as titled, thanks.

**Comment by SylvainDevidal** [comment]
Hello @RuiSoft2022 ,

You can compile *.pnml" files using NML Py-Patcher : https://www.tt-forums.net/viewtopic.php?t=83239
It mostly allows use includes files rather than having all the code in a single file.
You must install Python too. You can use this command line on Windows 10 & 11 :
winget install python

On my machine I created a folder "NML" with the NML compiler. Then in this directory I also created a folder "NML Py-Patcher" and placed the NML Py-Patcher files there.
Then in the NML folder I created a folder "SNCF" and pasted my source in it.
At last, I use those both scripts files to compiles :
make.bat (in the SNCF folder)

@echo off
call ../pybuild.bat sncf
copy /Y sncf.grf "<path to openttd>\newgrf"

And pybuild.bat (in the NML folder)
@ECHO OFF
call python nml_patcher.py -f "%1.pnml" -o "%1.nml" -b 0 -v 1
call nmlc "%1.nml" -o "%1.grf" -s

Enjoy 😃

**Comment by RuiSoft2022** [comment]
Thanks, @SylvainDevidal. I will have a try.
